# Generated by Django 3.0.7 on 2020-09-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='releasedate',
        ),
    ]
